services:
  api:
    build: .
    image: node
    container_name: booking-node
    ports:
      - "9000:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: database-mongo
    expose:
      - "27017"

