services:
  api:
    build: .
    image: node
    container_name: booking-hotel-node
    ports:
      - "9000:9000"
    depends_on:
      - mongo-booking

  mongo-booking:
    image: mongo
    container_name: db-mongo
    expose:
      - "27017:27017"

